### ISSUE TITLE
Find a replacement for tutum/redis

### ISSUE THREAD

**Issue by scottrobertson** [containerdb/containerdb#16]
The `tutum/redis` docker image has been deprecated, so we should find a replacement.

We cannot use the official one as it doesn't allow a password to be set.

We could just fork it and maintain it.

**Comment by marcqualie** [comment]
We could fork our own. I did this a few months ago for GoStatic.

Not only does it allow setting password, but supports master/slave out of the box based on env config

https://github.com/gostatic/docker-redis

**Comment by scottrobertson** [comment]
Yeah the go static one seems to do everything we need :)
