### ISSUE TITLE
Adding bootstrap-sass has doubled the size of the final slug

### ISSUE THREAD

**Issue by scottrobertson** [containerdb/containerdb#26]
I think we need a better way of doing this. Becuase we are compiling this down to a slug using build packs, it's including all of the SaaS gem in the final slug. We 100% don't need all of this at this point.

**Comment by marcqualie** [comment]
Even without the bootstrap-sass gem, you'd still need the sass gem for the asset pipeline. What has the size doubled to?

**Comment by marcqualie** [comment]
Where can I see/debug the size of the slug?

**Comment by scottrobertson** [comment]
Hey. It's in packager, or you can see the size when running apt-get install. It's not too much of an issue though, i would not worry about it too much :)
