### ISSUE TITLE
Add LetsEncrypt SSL Cert on install

### ISSUE THREAD

**Issue by scottrobertson** [containerdb/containerdb#27]

**Comment by marcqualie** [comment]
Any ideas on how to approach this? I find letsencrypt so hard to work with. Since it requires either DNS changes (big improvement but still hassle), or the domain to point to the server *before* the certificate is in place, I find it so hard to automate.

**Comment by scottrobertson** [comment]
@marcqualie since we request a hostname during install, we would just have to get them to point the domain to the server before trying to setup letsencrypt.
