### ISSUE TITLE
Health Checks

### ISSUE THREAD

**Issue by marcqualie** [containerdb/containerdb#35]
This is useful for current usage, but becomes much more required when added to concept of #31 

At any time a container could stop, error out, or become unresponsive and it would be good to monitor those at least on a very basic level of up vs down. Later we could add metrics such as latency/packet loss, send notifications.. etc

My MVP proposal:

- Add a status attribute with predefined values of:
  - online
  - offline
  - inactive (for when you want to turn it off on purpose, but not delete)
- Add a healthcheck attribute to services, jsonb format:
  - `{ 'interval': 30000, 'type': 'tcp', 'port': 6379, 'timeout': 5000 }`
  - empty health check config will disable it for that service
- Use clockwork to trigger a health check every X seconds (based on config)
- Use sidekiq to actually execute the health check calls and update the database

**Comment by scottrobertson** [comment]
Yeah, I like this idea. I do think we should leave the management of the containers to Docker at this point. For example, if one dies, we should not try and bring it back (docker will do that).

Would we just ping the container port for that service to check if it's active? Or does Docker have something built in?
