### ISSUE TITLE
Proposal to change backup system

### ISSUE THREAD

**Issue by scottrobertson** [containerdb/containerdb#40]
Right now we use each DB's method to backup. However, I was thinking, could we just snapshot the mounted volume directory? This would make backups super easy, and it would also make restoring very easy.

My only worry is how this works with DB's that are running etc. Is it safe to just snapshot the directory?

**Comment by scottrobertson** [comment]
@marcqualie what do you think? Any ideas?

**Comment by marcqualie** [comment]
I would depend on the DB in question, snapshitting while a DB is writing partial information to disk could lead to archive corruption. I'm sure there's ways to protect against that in the DB engine, but it impacts performance a bit I think and varies from engine to engine.

An idea for now would be to have a "snapshot" backup system that most use, then ones that don't support it they can use their own. The API for all backup solutions should be the same so how it actually performs it shouldn't matter, you just end up with a new instance and populated data to connect to.
